# Configuration file for processing CSV data.
# For more information about csv and mutate filter plugins, see the documentation:
# - https://www.elastic.co/docs/reference/logstash/plugins/plugins-filters-csv
# - https://www.elastic.co/docs/reference/logstash/plugins/plugins-filters-mutate

input {
    file {
        path => "/usr/share/logstash/ingest-data/csv-data/*"
        start_position => "beginning"
        sincedb_path => "/dev/null"
    }
}

filter {
    csv {
        separator => ","
        skip_header => true
        autodetect_column_names => true
        # Alternatively, provide column names as defined by the header column
        # columns => ["column1", "column2", ...]
        skip_empty_rows => true
    }
    mutate {
        #convert => {
        #    field_name => "integer"
        #}
        # Remove metadata fields
        remove_field => ["message", "@timestamp", "path", "host", "@version"]
    }
}

output {
    elasticsearch {
        hosts => "${ELASTIC_HOSTS}"
        user => "${ELASTIC_USER}"
        password => "${ELASTIC_PASSWORD}"
        ssl_enabled => true
        ssl_certificate_authorities => "${SSL_CERTIFICATEAUTHORITIES}"
        index => "csv_data"
    }
    stdout {}
}
