# Configuration file for processing Elasticsearch logs.
# For more information about the grok filter plugin, see the documentation:
# - https://www.elastic.co/docs/reference/logstash/plugins/plugins-filters-grok
# For more information about the multiline codec plugin, see the documentation:
# - https://www.elastic.co/docs/reference/logstash/plugins/plugins-codecs-multiline

input {
    file {
        path => "/usr/share/logstash/ingest-data/elasticsearch-logs/*"
        type => "elasticsearch"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        codec => multiline {
            pattern => "^\["
            negate => true
            what => "previous"
        }
    }
}

filter {
    if [type] == "elasticsearch" {
        grok {
            match => {"message" => "\[%{TIMESTAMP_ISO8601:timestamp}\]\[%{DATA:severity}%{SPACE}\]\[%{DATA:source}%{SPACE}\]%{SPACE}(?<message>(.|\r|\n)*)"}
            overwrite => ["message"]
        }
        if "_grokparsefailure" not in [tags] {
            grok {
                match => {
                    "message" => [
                        "^\[%{DATA:node}\] %{SPACE}\[%{DATA:index}\]%{SPACE}(?<short_message>(.|\r|\n)*)",
                        "^\[%{DATA:node}\]%{SPACE}(?<short_message>(.|\r|\n)*)"
                    ]
                }
                tag_on_failure => []
            }
        }
    }
}

output {
    elasticsearch {
        hosts => "${ELASTIC_HOSTS}"
        user => "${ELASTIC_USER}"
        password => "${ELASTIC_PASSWORD}"
        ssl_enabled => true
        ssl_certificate_authorities => "${SSL_CERTIFICATEAUTHORITIES}"
        index => "es_logs"
    }
    stdout {
        codec => rubydebug
    }
}
