# Configuration file for processing JSON data.
# For more information about json, mutate, split, and drop filter plugins, see the documentation:
# - https://www.elastic.co/docs/reference/logstash/plugins/plugins-filters-json
# - https://www.elastic.co/docs/reference/logstash/plugins/plugins-filters-mutate
# - https://www.elastic.co/docs/reference/logstash/plugins/plugins-filters-split
# - https://www.elastic.co/docs/reference/logstash/plugins/plugins-filters-drop

input {
    file {
        path => "/usr/share/logstash/ingest-data/json-data/*"
        start_position => "beginning"
        sincedb_path => "/dev/null"
    }
}

filter {
    json {
        source => "message"
        skip_on_invalid_json => true
    }
    #if [field_name] == value {
    #    drop {}
    #}
    #split {
    #    field => "[array_name]"
    #}
    mutate {
        #add_field => {
        #    "field1_name" => "%{[array_name][field1_name]}"
        #    "field2_name" => "%{[array_name][field2_name]}"
        #}
        # Remove metadata fields
        # You can also include "array_name" to remove the original array field
        remove_field => ["message", "@timestamp", "path", "host", "@version"]
    }
}

output {
    elasticsearch {
        hosts => "${ELASTIC_HOSTS}"
        user => "${ELASTIC_USER}"
        password => "${ELASTIC_PASSWORD}"
        ssl_enabled => true
        ssl_certificate_authorities => "${SSL_CERTIFICATEAUTHORITIES}"
        index => "json_data"
    }
    stdout {}
}
