# Configuration file for processing Apache logs.
# For more information about the used filter plugins, see the documentation:
# - https://www.elastic.co/docs/reference/logstash/plugins/plugins-filters-grok
# - https://www.elastic.co/docs/reference/logstash/plugins/plugins-filters-useragent
# - https://www.elastic.co/docs/reference/logstash/plugins/plugins-filters-geoip
# - https://www.elastic.co/docs/reference/logstash/config-examples
# NOTE: COMBINEDAPACHELOG and HTTPD_COMBINEDLOG patterns in grok filter plugin differ depending on the pipeline.ecs_compatibility setting:
# - https://github.com/logstash-plugins/logstash-patterns-core/blob/main/patterns/ecs-v1/httpd
# - https://github.com/logstash-plugins/logstash-patterns-core/blob/main/patterns/legacy/httpd
# For more information about ECS in Logstash, see https://www.elastic.co/docs/reference/logstash/ecs-ls

input {
    file {
        path => "/usr/share/logstash/ingest-data/apache-logs/*"
        start_position => "beginning"
        sincedb_path => "/dev/null"
    }
}

filter {
    grok {
        ecs_compatibility => "v8"
        match => {"message" => ["%{COMBINEDAPACHELOG}", "%{HTTPD_COMBINEDLOG}"]}
        remove_field => ["message"]
    }
    mutate {
        add_field => {"read_timestamp" => "%{@timestamp}"}
        remove_field => ["log", "host", "@version", "event"]
    }
    date {
        match => ["timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
        remove_field => "timestamp"
    }
    if [source][address] {
        geoip { source => "[source][address]" target => "[source]" ecs_compatibility => "v8" }
    } else if [client][ip] {
        geoip { source => "[client][ip]" target => "[client]" ecs_compatibility => "v8" }
    }
    if [user_agent][original] {
        useragent { source => "[user_agent][original]" target => "[user_agent]" ecs_compatibility => "v8" }
    }
}

output {
    elasticsearch {
        hosts => "${ELASTIC_HOSTS}"
        user => "${ELASTIC_USER}"
        password => "${ELASTIC_PASSWORD}"
        ssl_enabled => true
        ssl_certificate_authorities => "${SSL_CERTIFICATEAUTHORITIES}"
        index => "apache_logs"
    }
    stdout {
        codec => rubydebug
    }
}
