input {
    file {
        path => "/usr/share/logstash/ingest-data/apache-logs/*"
        start_position => "beginning"
    }
}

filter {
    grok {
        match => {"message" => "%{COMBINEDAPACHELOG}"}
    }
    date {
        match => ["timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
    }
}

output {
    elasticsearch {
        hosts => "${ELASTIC_HOSTS}"
        user => "${ELASTIC_USER}"
        password => "${ELASTIC_PASSWORD}"
        ssl_enabled => true
        ssl_certificate_authorities => "${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"
    }
    stdout {
        codec => rubydebug
    }
}
